import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1789421034910 implements MigrationInterface {
  name = 'InitialSchema1789421034910';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "orders" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" bigint NOT NULL, "status" text NOT NULL DEFAULT 'created', "total_cents" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "chk_orders_status" CHECK ("status" IN ('created', 'paid', 'cancelled')), CONSTRAINT "chk_orders_total_non_negative" CHECK ("total_cents" >= 0), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "order_items" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "order_id" bigint NOT NULL, "product_id" bigint NOT NULL, "quantity" integer NOT NULL, "unit_price_cents" integer NOT NULL, CONSTRAINT "uq_order_items_order_product" UNIQUE ("order_id", "product_id"), CONSTRAINT "chk_order_items_unit_price_non_negative" CHECK ("unit_price_cents" >= 0), CONSTRAINT "chk_order_items_quantity_positive" CHECK ("quantity" > 0), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "products" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "owner_id" bigint NOT NULL, "name" text NOT NULL, "description" text, "price_cents" integer NOT NULL, "available" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "chk_products_price_cents_non_negative" CHECK ("price_cents" >= 0), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "users" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" text NOT NULL, "name" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_email" ON "users" ("email") `);
    await queryRunner.query(
      `ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "products" ADD CONSTRAINT "FK_47f06db8065c55a363b6db3ae82" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(`
  CREATE INDEX "idx_orders_user_created_at"
  ON "orders" ("user_id", "created_at" DESC)
`);

    await queryRunner.query(`
  CREATE INDEX "idx_orders_created_created_at"
  ON "orders" ("created_at" DESC)
  WHERE "status" = 'created'
`);

    await queryRunner.query(`
  CREATE INDEX "idx_products_lower_name"
  ON "products" (lower("name"))
`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "products" DROP CONSTRAINT "FK_47f06db8065c55a363b6db3ae82"`,
    );
    await queryRunner.query(
      `ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`,
    );
    await queryRunner.query(
      `ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`,
    );
    await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
    await queryRunner.query(`
      DROP INDEX "idx_products_lower_name"
    `);

    await queryRunner.query(`
      DROP INDEX "idx_orders_created_created_at"
    `);

    await queryRunner.query(`
      DROP INDEX "idx_orders_user_created_at"
    `);
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(`DROP TABLE "products"`);
    await queryRunner.query(`DROP TABLE "order_items"`);
    await queryRunner.query(`DROP TABLE "orders"`);
  }
}
