import { MigrationInterface, QueryRunner } from 'typeorm';

export class CheckoutConcurrency1790779141634 implements MigrationInterface {
  name = 'CheckoutConcurrency1790779141634';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "checkout_jobs" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "order_id" bigint NOT NULL, "type" text NOT NULL DEFAULT 'send_receipt', "payload" jsonb NOT NULL, "status" text NOT NULL DEFAULT 'pending', "processed_count" integer NOT NULL DEFAULT '0', "processed_by" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "processed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "chk_checkout_jobs_processed_count" CHECK ("processed_count" >= 0), CONSTRAINT "chk_checkout_jobs_status" CHECK ("status" IN ('pending', 'done')), CONSTRAINT "PK_5d32cf5bf3f3f1da1888d6ad9ce" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_checkout_jobs_status_id" ON "checkout_jobs" ("status", "id") `,
    );
    await queryRunner.query(`ALTER TABLE "products" ADD "stock" integer NOT NULL DEFAULT '0'`);
    await queryRunner.query(`ALTER TABLE "users" ADD "balance_cents" integer NOT NULL DEFAULT '0'`);
    await queryRunner.query(
      `ALTER TABLE "products" ADD CONSTRAINT "chk_products_stock_non_negative" CHECK ("stock" >= 0)`,
    );
    await queryRunner.query(
      `ALTER TABLE "users" ADD CONSTRAINT "chk_users_balance_non_negative" CHECK ("balance_cents" >= 0)`,
    );
    await queryRunner.query(
      `ALTER TABLE "checkout_jobs" ADD CONSTRAINT "FK_138a5bbd47369cf0f3d198c591c" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "checkout_jobs" DROP CONSTRAINT "FK_138a5bbd47369cf0f3d198c591c"`,
    );
    await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "chk_users_balance_non_negative"`);
    await queryRunner.query(
      `ALTER TABLE "products" DROP CONSTRAINT "chk_products_stock_non_negative"`,
    );
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "balance_cents"`);
    await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "stock"`);
    await queryRunner.query(`DROP INDEX "public"."idx_checkout_jobs_status_id"`);
    await queryRunner.query(`DROP TABLE "checkout_jobs"`);
  }
}
